repos:
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    - id: isort
      additional_dependencies: ["toml"]
      language_version: python3.10
-   repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
    - id: black
      language_version: python3.10
-   repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.3
    hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
      language_version: python3.10
